   - name: Install MySQL database
     apt: name={{ item }} state=present
     with_items:
       - mariadb-server
       - mariadb-client

   - name: Install pymysql package
     pip:
       name: '{{ python_mysql_pack_name }}'
       state: present

   - name: Start MySQL DB
     service:
       name: '{{ service_mysql_name }}'
       state: started
       enabled: yes

